jobmanager.rpc.address: flink-jobmanager
jobmanager.rpc.port: 6123
jobmanager.memory.process.size: 1600m
taskmanager.memory.process.size: 1728m
taskmanager.numberOfTaskSlots: 1
parallelism.default: 1
state.backend: hashmap
state.checkpoints.dir: file:///opt/flink/checkpoints
state.savepoints.dir: file:///opt/flink/savepoints
high-availability: none
# high-availability.storageDir: file:///opt/flink/ha/
high-availability.zookeeper.quorum: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
high-availability.zookeeper.path.root: /flink
blob.server.port: 6124
query.server.port: 6125
rest.port: 8081
rest.address: 0.0.0.0
classloader.resolve-order: parent-first
web.submit.enable: true